### ISSUE TITLE
NNF ATR does not calculate correct LOT size for Yen pairs (and similar)

### ISSUE THREAD

**Issue by cajuncoder** [rpsreal/No_Nonsense_ATR#1]
Hello,

I've been placing trades directly on Oanda's interface where they make it easy. I downloaded the NNF ATR to help me place trades directly inside of MT4. However, as I understand it:

1 lot = 100,000 units.
When I place my trade, for a $4000 account on Oanda with a stop loss of 40, I get 10,000 units as the correct amount. This is verifiable as, when I look at where my stop loss is, it is at 1ATR: where I normally place my SL. However:

The NNFATR gives me a lot size of 0.001, and I get the error that this exceeds my broker's minimum of 0.01 lots. So that would be... 100 units.
It's off by two 0's

Please confirm.

**Comment by cajuncoder** [comment]
Double checked with this position size calculator:
https://www.babypips.com/tools/position-size-calculator

Both it and Oanda confirm that I am getting the wrong lot size on CHFJPY.

**Comment by hunter548** [comment]
This issue affects all currencies and not just Yen pairs. I verified it as well comparing it to both a pos_size.mq4 indicator and a manual calculation for the correct outcome.

**Comment by rpsreal** [comment]
Hi @cajuncoder and @hunter548, sorry for the late reply.
Make sure you configure the NN ATR correctly, NN ATR has tested on 36 forex pairs and works correctly on all of them. You can see in the following images, on the CHFJPY and GBPJPY pairs that NN ATR calculates the position size/trading volume correctly.
CHFJPY :
![NN ATR_ chfjpy](https://user-images.githubusercontent.com/11331425/71828015-6ae8e980-3099-11ea-802b-4f4c9d6b8667.png)
GBPJPY :
![NN ATR_ gbpjpy](https://user-images.githubusercontent.com/11331425/71828022-6de3da00-3099-11ea-8f01-8f2415a03e21.png)

Regards,
Rui Silva
