### ISSUE TITLE
NNATR Indi request buffer for Trading Bot

### ISSUE THREAD

**Issue by crossfire81** [rpsreal/No_Nonsense_ATR#2]
Just want to first off say love your work. Awesome to have people like you around.
I'm currently using fxDreema to build trading bots and some of the programming blocks require buffer info to execute events.
With the latest version it only shows buffer for SL.
If possible could you please add TP buffer as well.
Much appreciated. 
Johann.

**Comment by rpsreal** [comment]
Hi Johann,
I'm glad you like using the NN ATR.
Regarding the buffers, both of the 3 buffers work in the 5.80 version, no changes were made in this aspect.
Just notice that to access the SL buffer you must use the value 1, and the value 0 to access the TP buffer. You can find out more about it here: https://nnfxalgotester.com/help/no-nonsense-atr/#icustom

King Regards,
Rui Silva
